package output

import (
	"regexp"
	"strings"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repository Diagram</title>
    <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: #f5f5f5;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 2rem;
        }
        h1 {
            color: #333;
            margin-bottom: 1.5rem;
            font-size: 1.5rem;
        }
        .mermaid {
            background: white;
            padding: 2rem;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            max-width: 100%;
            overflow: auto;
        }
        .mermaid svg {
            max-width: 100%;
            height: auto;
        }
        .footer {
            margin-top: 2rem;
            color: #666;
            font-size: 0.875rem;
        }
        .footer a {
            color: #0066cc;
            text-decoration: none;
        }
        .footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h1>Repository Architecture Diagram</h1>
    <pre class="mermaid">
{{DIAGRAM}}
    </pre>
    <p class="footer">Generated by <a href="https://humbledshuttler.com/repodiagram">repodiagram</a></p>
    <script>
        mermaid.initialize({
            startOnLoad: true,
            theme: 'neutral',
            flowchart: {
                useMaxWidth: true,
                htmlLabels: true,
                curve: 'basis'
            },
            securityLevel: 'loose'
        });
    </script>
</body>
</html>`

func ToHTML(diagram string) string {
	return strings.Replace(htmlTemplate, "{{DIAGRAM}}", diagram, 1)
}

func RemoveClickEvents(diagram string) string {
	re := regexp.MustCompile(`(?m)^\s*click\s+\S+\s+"[^"]*"\s*$\n?`)
	return re.ReplaceAllString(diagram, "")
}
